### ISSUE TITLE
Consider dropping from php-7.0 to php-7.2 supports

### ISSUE THREAD

**Issue by peter279k** [stevegrunwell/phpunit-markup-assertions#22]
As title, since the `php-7.0`, `php-7.1` and `php-7.2` versions are end of life.

And it should drop them and let this package require `php-7.3` version at least.

**Comment by stevegrunwell** [comment]
Hi @peter279k, thanks for the suggestion (and multiple other issues/PRs across my repos that I need to sort through 😉)!

I'm all for pushing people to the latest and greatest versions of PHP, but it becomes a little more challenging when building testing tools, as I don't get to control what other people are using.

For example, both this repository and [assertwell/phpunit-global-state](https://github.com/assertwell/phpunit-global-state) were born out of a need to test features rolled out on our Managed WordPress/WooCommerce platforms at @nexcess. Those platforms currently support PHP versions back to 5.6 (much to my chagrin), so raising the minimum PHP version for the testing tools would mean I'd no longer be able to use them to test across all of the versions we support.

When I'm building testing tools, my goal is to lower the barrier of entry to automated software testing. In this library's case, I needed to test the output of some WordPress shortcodes without adding the overhead of a headless browser; instead of burying the logic inside a single project's test suite, I extracted it into a library that anyone can use (and I can more-easily reuse across projects).

Until such a time that maintaining backwards compatibility with PHP 5.6 becomes burdensome (or [if WordPress finally drops PHP 5.6](https://make.wordpress.org/core/2020/08/24/proposal-dropping-support-for-old-php-versions-via-a-fixed-schedule/)), I want to ensure that the test-oriented tools that I build are useful for as many people as possible.
